### ISSUE TITLE
Release new version to rubygems

### ISSUE THREAD

**Issue by thisissmithj** [Juniper/ruby-junos-ez-stdlib#19]
Git HEAD fixes a number of issues which should be released to the official rubygems version. Notably, I was just affected by https://github.com/Juniper/ruby-junos-ez-stdlib/pull/15, which was merged months ago. Could we get a 0.1.3 or 0.2 released to rubygems?

Thanks!

**Comment by twheele** [comment]
Please.

**Comment by ganeshnalawade** [comment]
@thisissmithj @twheele We will update to a new version soon.

**Comment by klieth** [comment]
@ganeshnalawade what's the status on this?

**Comment by thisissmithj** [comment]
Any update?

**Comment by yli-square** [comment]
Looking forward to update

**Comment by jercawley** [comment]
+1

**Comment by thisissmithj** [comment]
@ganeshnalawade Any update on a release?

**Comment by ganeshnalawade** [comment]
@thisissmithj We are facing few issues to release latest version in rubygems, work is in progress to get it resolved.

**Comment by thisissmithj** [comment]
bump.

**Comment by PeiwenChen** [comment]
Can you push the latest release to RubyGem?

**Comment by routelastresort** [comment]
Updated to latest version/pushed.
