### ISSUE TITLE
cannot get the git source code

### ISSUE THREAD

**Issue by PeiwenChen** [Juniper/ruby-junos-ez-stdlib#47]
@ganeshnalawade  
Hi, 

Because the rubyGem is not updated, so I am trying to get this repo source code but failed. Can you resolve it?

I added this line in my repo Gemfil:
`
gem 'ruby-junos-ez-stdlib', github: 'juniper/ruby-junos-ez-stdlib', ref: '0d1ecb14cb5bfdd02ceebbe5888221f37e05eefd'`

And these are the errors I saw:
```
bundle
Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Fetching git://github.com/juniper/ruby-junos-ez-stdlib.git
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Could not find gem 'ruby-junos-ez-stdlib (>= 0) ruby' in git://github.com/juniper/ruby-junos-ez-stdlib.git (at 0d1ecb1).
Source does not contain any versions of 'ruby-junos-ez-stdlib (>= 0) ruby'
```

**Comment by ganeshnalawade** [comment]
@PeiwenChen 
Please follow below steps to install gems from Github source.
```
% git clone https://github.com/Juniper/ruby-junos-ez-stdlib.git
% cd ruby-junos-ez-stdlib
% gem build junos-ez-stdlib.gemspec
% sudo gem install junos-ez-stdlib-1.0.0.gem
```

**Comment by PeiwenChen** [comment]
@ganeshnalawade But this is to manually install the gem.

When are you going to release the latest to rubyGem?

**Comment by routelastresort** [comment]
Gem updated to 1.0.0 on Rubygems
